### ISSUE TITLE
Functional tests not upstreamed?

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/charm-cinder-backup-swift#5]
https://github.com/openstack-charmers/charm-cinder-backup-swift/blob/bc764aa10cfb52f8405c45c78b73349966eb13f5/tests/tests.yaml#L11

There appears to be a reference to Zaza functional tests but I do not find them in the upstream repositories.

Would you mind opening a PR on https://github.com/openstack-charmers/zaza-openstack-tests with the setup and test code.

Note that OpenStack tests should be prefixed by the ``zaza.openstack`` module path, and you need to add both the ``zaza`` and ``zaza-openstack-tests`` repositories to ``src/test-requirements.txt``

The amulet tests should also be removed.

**Comment by lolwww** [comment]
Hi Frode.
Here is pull request for tests
https://github.com/openstack-charmers/zaza-openstack-tests/pull/24

And one attached for charm itself (removes amulet and fixes issues found during testing)
With that I get following results
https://pastebin.canonical.com/p/dCW32qdyJ3/

**Comment by fnordahl** [comment]
Great, I'll leave this issue open until the last fixes are dealt with in openstack-charmers/zaza-openstack-tests#24 and validated on a OpenStack substrate.

The current bundles uses LXD placement and reference hardware specifc devices, please update bundles.

Here is a working example:
```
series: bionic
relations:
- - nova-compute:amqp
  - rabbitmq-server:amqp
- - keystone:shared-db
  - mysql:shared-db
- - nova-cloud-controller:identity-service
  - keystone:identity-service
- - glance:identity-service
  - keystone:identity-service
- - glance:shared-db
  - mysql:shared-db
- - glance:amqp
  - rabbitmq-server:amqp
- - nova-cloud-controller:image-service
  - glance:image-service
- - nova-compute:image-service
  - glance:image-service
- - nova-cloud-controller:cloud-compute
  - nova-compute:cloud-compute
- - nova-cloud-controller:amqp
  - rabbitmq-server:amqp
- - nova-cloud-controller:shared-db
  - mysql:shared-db
- - cinder:image-service
  - glance:image-service
- - cinder:amqp
  - rabbitmq-server:amqp
- - cinder:identity-service
  - keystone:identity-service
- - cinder:cinder-volume-service
  - nova-cloud-controller:cinder-volume-service
- - cinder-ceph:storage-backend
  - cinder:storage-backend
- - cinder
  - cinder-backup-swift
- - ceph-mon:client
  - nova-compute:ceph
- - nova-compute:ceph-access
  - cinder-ceph:ceph-access
- - cinder:shared-db
  - mysql:shared-db
- - ceph-mon:client
  - cinder-ceph:ceph
- - ceph-mon:client
  - glance:ceph
- - ceph-osd:mon
  - ceph-mon:osd

# external swift service
- - swift-keystone:shared-db
  - swift-mysql:shared-db
- - swift-proxy:identity-service
  - swift-keystone:identity-service
- - swift-proxy:swift-storage
  - swift-storage:swift-storage

applications:
  ceph-mon:
    series: bionic
    charm: cs:ceph-mon
    num_units: 3
    options:
      monitor-count: '3'
  ceph-osd:
    series: bionic
    charm: cs:ceph-osd
    num_units: 3
    storage:
      osd-devices: 'cinder,10G'
  cinder:
    series: bionic
    charm: cs:cinder
    num_units: 1
    options:
      block-device: None
      glance-api-version: 2
  cinder-ceph:
    series: bionic
    charm: cs:cinder-ceph
    num_units: 0
  cinder-backup-swift:
    series: bionic
    charm: cinder-backup-swift
    num_units: 0
    options:
      auth-version: 3
      swift-user: admin
      swift-key: openstack
      user-domain: admin_domain
      project-domain: admin_domain
      project-name: admin
  glance:
    series: bionic
    charm: cs:glance
    num_units: 1
  keystone:
    series: bionic
    charm: cs:keystone
    num_units: 1
  mysql:
    series: bionic
    charm: cs:percona-cluster
    num_units: 1
    options:
      dataset-size: 25%
      max-connections: 1000
  nova-cloud-controller:
    series: bionic
    charm: cs:nova-cloud-controller
    num_units: 1
  rabbitmq-server:
    series: bionic
    charm: cs:rabbitmq-server
    num_units: 1
  nova-compute:
    series: bionic
    charm: cs:nova-compute
    num_units: 1

# external swift
  swift-keystone:
    charm: cs:keystone
    num_units: 1
    options:
      admin-password: openstack
  swift-mysql:
    charm: cs:percona-cluster
    num_units: 1
    options:
      dataset-size: 25%
      max-connections: 1000
  swift-proxy:
    charm: cs:swift-proxy
    num_units: 1
    options:
      zone-assignment: manual
      replicas: 1
  swift-storage:
    charm: cs:swift-storage
    num_units: 1
    options:
      zone: 1
    storage:
      block-devices: 'cinder,10G'
```
